server:
  port: 8085
#基本语法
#  k:(空格)v:表示一堆键值对（空格必须有）
#  用空格的锁紧来控制层级关系，只要是左对齐的一些属性，都是同一个层级的

spring:
  profiles:
    active: prod
---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: dev #指定属于哪个环境
---
server:
  port: 8084

spring:
  config:
    activate:
      on-profile: prod
---
#person:
#  lastname: zhangsan
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: v2}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    lastName: xiaogou
#    age: 2

